CREATE TABLE `app_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text,
	`default_payment_terms` integer DEFAULT 30,
	`default_vat_rate` real DEFAULT 20,
	`invoice_prefix` text DEFAULT 'INV',
	`next_invoice_number` integer DEFAULT 1,
	`estimate_prefix` text DEFAULT 'EST',
	`next_estimate_number` integer DEFAULT 1,
	`currency` text DEFAULT 'GBP',
	`date_format` text DEFAULT 'DD/MM/YYYY',
	`number_format` text DEFAULT 'en-GB',
	`auto_calculate_quarters` integer DEFAULT true,
	`quarterly_tax_enabled` integer DEFAULT true,
	`quarter_start_months` text DEFAULT '1,4,7,10',
	`quarterly_tax_reminder_days` integer DEFAULT 7,
	`financial_year_start_month` integer DEFAULT 1,
	`financial_year_start_day` integer DEFAULT 1,
	`financial_year_end_month` integer DEFAULT 12,
	`financial_year_end_day` integer DEFAULT 31,
	`tax_scheme` text DEFAULT 'standard',
	`default_tax_category` text DEFAULT 'self-employed',
	`reminder_email_enabled` integer DEFAULT true,
	`reminder_days_before_due` integer DEFAULT 3,
	`language` text DEFAULT 'en-GB',
	`theme` text DEFAULT 'system',
	`logo_url` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`user_id`) REFERENCES `User`(`id`) ON UPDATE no action ON DELETE no action
);
